name: UpdateHosts

on:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build-sh
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 
          chmod +x ./git_hosts.sh
          chmod +x ./hosts
          ./git_hosts.sh ./hosts 

      - name: Commit
        id: commit
        run: |
          git config --global user.email Rexexe@git.com
          git config --global user.name Rexexe
          git add .
          git commit -m "Update hosts"
        continue-on-error: true

      - name: Check on failures
        if: steps.commit.outputs.status == 'failure'
        run: exit 1

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
